import { ObjectId } from "mongodb";
import {
  getCelebrityFactsAutoGenerationConfig,
  createCelebrityFactsAutoGenerationJob,
  updateCelebrityFactsJobStatus,
  incrementCelebrityFactsGeneratedCount,
  CelebrityFactsAutoGenerationJob,
} from "@/lib/db/auto-generation-celebrity-facts";
import { addScheduledVideo } from "@/lib/db/users";
import { markCelebrityFactStatus } from "@/lib/celebrity-facts/storage";
import { selectNextCelebrityFact, getAvailableCelebrityFactsCount } from "./celebrity-facts-selector";
import { prepareAudioCut, selectRandomFromArray } from "./audio-processor";
import { renderCelebrityFactsVideo } from "@/lib/video/renderer-new";
import { generateNewsShortsTitle, generateNewsShortsDescription } from "@/lib/youtube/title-generator";

/**
 * Extract two photo URLs from the fact's sourceLinks.
 * sourceLinks are expected to be direct image URLs (e.g. Wikimedia).
 */
function getImagesFromSourceLinks(sourceLinks: string[]): [string, string] {
  const url1 = sourceLinks[0];
  const url2 = sourceLinks[1] ?? sourceLinks[0]; // Use same image twice if only one link
  return [url1, url2];
}

/**
 * Main function to generate a celebrity facts video
 */
export async function generateCelebrityFactsVideo(
  userId: string,
  configId: string,
  scheduledAt: Date,
  specificFactId?: string
): Promise<CelebrityFactsAutoGenerationJob> {
  const jobId = new ObjectId().toString();

  console.log(`\n=== Starting Celebrity Facts Video Generation ===`);
  console.log(`Job ID: ${jobId}, User: ${userId}`);

  try {
    // 1. Get config
    const config = await getCelebrityFactsAutoGenerationConfig(userId);
    if (!config) throw new Error("Celebrity facts auto-generation config not found");
    if (!specificFactId && !config.isEnabled) throw new Error("Celebrity facts auto-generation is disabled");

    // 2. Check available facts
    if (!specificFactId) {
      const available = await getAvailableCelebrityFactsCount();
      if (available === 0) throw new Error("No celebrity facts available for generation");
    }

    // 3. Reserve fact
    let fact;
    if (specificFactId) {
      const { findCelebrityFactById, markCelebrityFactStatus: markStatus } = await import("@/lib/celebrity-facts/storage");
      fact = await findCelebrityFactById(specificFactId);
      if (!fact) throw new Error(`Celebrity fact ${specificFactId} not found`);
      await markStatus({ id: specificFactId, status: "reserved" });
    } else {
      fact = await selectNextCelebrityFact();
    }
    if (!fact) throw new Error("Failed to reserve celebrity fact");

    console.log(`Selected fact: "${fact.title}"`);

    // 4. Use title directly as short headline (pre-generated by agent)
    const shortHeadline = fact.title.length > 80 ? fact.title.substring(0, 77) + "..." : fact.title;
    console.log(`Short headline: ${shortHeadline}`);

    // 5. Get two images from sourceLinks
    if (!fact.sourceLinks || fact.sourceLinks.length === 0) {
      throw new Error(`Celebrity fact ${fact._id} has no sourceLinks (photos)`);
    }
    const [imageUrl1, imageUrl2] = getImagesFromSourceLinks(fact.sourceLinks);
    console.log(`Image 1: ${imageUrl1}`);
    console.log(`Image 2: ${imageUrl2}`);

    // 6. Prepare audio
    let audioUrl: string | undefined;
    let audioTrimStart: number | undefined;
    let audioTrimEnd: number | undefined;

    if (config.template.audio && config.template.audio.urls.length > 0) {
      const selectedAudioUrl = selectRandomFromArray(config.template.audio.urls);
      const targetDuration = config.template.audio.duration || 8;
      if (selectedAudioUrl) {
        if (config.template.audio.randomTrim) {
          const audioCut = await prepareAudioCut(selectedAudioUrl, targetDuration, true);
          audioUrl = selectedAudioUrl;
          audioTrimStart = audioCut.start;
          audioTrimEnd = audioCut.end;
        } else {
          audioUrl = selectedAudioUrl;
          audioTrimStart = 0;
          audioTrimEnd = targetDuration;
        }
      }
    }

    // 7. Create job record
    const job = await createCelebrityFactsAutoGenerationJob({
      userId,
      configId: String(config._id),
      status: "processing",
      factId: String(fact._id),
      factTitle: fact.title,
      factText: fact.text,
      imageHashtags: fact.imageHashtags,
      selectedResources: { audioUrl, audioTrimStart, audioTrimEnd },
      retryCount: 0,
    });

    // 8. Render video
    const renderResult = await renderCelebrityFactsVideo({
      imageUrl1,
      imageUrl2,
      shortHeadline,
      factText: fact.text,
      audioUrl,
      audioTrimStart,
      audioTrimEnd,
      duration: config.template.audio?.duration || 8,
      templateId: config.selectedTemplate || "template1",
      blackAndWhite: config.blackAndWhitePhotos ?? false,
      jobId,
    });

    // 9. Generate YouTube metadata
    let youtubeTitle = fact.title;
    let youtubeDescription = fact.text;

    if (config.youtube.useAI) {
      try {
        const [genTitle, genDesc] = await Promise.all([
          generateNewsShortsTitle(fact.title, fact.text),
          generateNewsShortsDescription(fact.title, fact.text),
        ]);
        youtubeTitle = genTitle;
        youtubeDescription = genDesc;
      } catch (aiErr) {
        console.error("AI metadata generation failed, using fallback:", aiErr);
      }
    }

    // Add music attribution if audio is used
    if (audioUrl) {
      let trackName = "Track";
      try {
        const fileName = decodeURIComponent(audioUrl.split("/").pop()?.split("?")[0] || "");
        if (fileName.endsWith(".mp3")) {
          trackName = fileName.replace(".mp3", "").replace(/[-_]/g, " ");
        }
      } catch { /* use default */ }
      youtubeDescription += `\n\nMusic: "${trackName}" by Kevin MacLeod (incompetech.com)\nLicensed under Creative Commons: By Attribution 4.0 License\nhttp://creativecommons.org/licenses/by/4.0/`;
    }

    // 10. Schedule video
    const channelIdToUse =
      config.youtube.savedChannelId ||
      config.youtube.manualChannelId ||
      config.youtube.channelId;

    const scheduledVideo = await addScheduledVideo(userId, {
      videoUrl: renderResult.videoUrl,
      title: youtubeTitle,
      description: youtubeDescription,
      tags: config.youtube.tags || ["datoscuriosos", "famosos", "celebridades", "shorts", "españa", "sabíasque"],
      privacyStatus: config.youtube.privacyStatus || "public",
      scheduledAt,
      youtubeChannelId: channelIdToUse,
      language: "es",
    });

    // 11. Update job
    await updateCelebrityFactsJobStatus(job._id!, "completed", {
      results: {
        renderedVideoUrl: renderResult.videoUrl,
        scheduledVideoId: scheduledVideo.id,
        scheduledAt,
      },
    });

    // 12. Mark fact as used
    await markCelebrityFactStatus({ id: fact._id, status: "used" });

    // 13. Increment counter
    await incrementCelebrityFactsGeneratedCount(config._id!);

    console.log(`=== Celebrity Facts Video Generation Completed ===`);
    return job;
  } catch (error) {
    console.error(`=== Celebrity Facts Video Generation Failed ===`, error);

    try {
      const failedJob = await createCelebrityFactsAutoGenerationJob({
        userId,
        configId,
        status: "failed",
        factId: "",
        factTitle: "",
        factText: "",
        imageHashtags: [],
        selectedResources: {},
        errorMessage: error instanceof Error ? error.message : String(error),
        retryCount: 0,
      });
      return failedJob;
    } catch (dbErr) {
      console.error("Failed to create error job record:", dbErr);
      throw error;
    }
  }
}
